version: 0.2

env:
  variables:
    APP: "twilio"
    BUCKET: "process-messages"
    DEPLOY_BRANCH: "dev"
    FUNCTION_NAME: "twilio_lambda"
    REGION: "us-west-2"

phases:
  build:
    commands:
      - echo Entered the build phase...
      - cd lambda/$APP
      - mkdir -p dependencies
      - pip3 install -r requirements.txt -t ./dependencies  
      - cd dependencies
      - commitID=$(git rev-parse HEAD)
      - zip -r9 "./../${commitID}.zip" .
      - cd -
      - zip -g ${commitID}.zip Integration.py
    finally:
      - echo Build complete
  post_build:
    commands:
      - echo Entered the post_build phase...
      - sh deploy.sh --commitID $commitID --branch $DEPLOY_BRANCH
    finally:
      - echo "Deploy complete"
