version: 0.2

env:
  variables:
    APP: "youtube"
    FUNCTION_NAME: "youtube_lambda"
    BUCKET: "process-messages"

phases:
  build:
    commands:
      - echo Entered the build phase...
      - cd lambda/$APP
      - rm -rf dependencies
      - rm -f Integration.zip
      - mkdir -p dependencies  
      - pip3 install -r requirements.txt -t ./dependencies  
      - cd dependencies
      - zip -r9 "./../Integration.zip" .
      - cd -
      - zip -g Integration.zip Integration.py
    finally:
      - echo Build complete
  post_build:
    commands:
      - echo Entered the post_build phase...
      - aws s3 cp Integration.zip s3://$BUCKET/$APP/
      - aws lambda update-function-code --function-name $FUNCTION_NAME --s3-bucket $BUCKET --s3-key $APP/Integration.zip --region us-west-2
    finally:
      - echo "Deploy complete"
